source 'http://rubygems.org'

ruby "2.3.1"

gem "sinatra"
gem "activerecord"
gem "sinatra-activerecord"
gem 'rake'

group :development do
  gem "shotgun"
  gem "tux"
  gem 'sqlite3'
end

group :production do
  gem 'pg'
end
