source 'https://rubygems.org'

ruby '2.3.1'

gem 'bundler'
gem 'sinatra'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'tilt-jbuilder', require: 'sinatra/jbuilder'
gem 'rake'
gem 'faker'

group :development do
  gem 'sqlite3'
end

group :production do
  gem 'pg'
end

group :test do
  gem 'rspec'
  gem 'rack-test'
end
