source 'https://rubygems.org'
ruby '2.4.0'

gem 'sinatra'
gem 'rake'
gem 'redcarpet'
gem 'pygments.rb'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'json'
gem 'thin'
gem 'rack'
gem 'sinatra-reloader'


group :development do
  gem 'shotgun'
  gem 'sqlite3'
end

group :production do
  gem 'pg'
end

group :test do
  gem 'rspec'
  gem 'rack-test'
end

