source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-reloader'


gem 'rake', '~> 10.4', '>= 10.4.2'
gem 'activerecord', '~> 4.2', '>= 4.2.5'
gem 'pry', '~> 0.10.3'
gem 'sqlite3', '~> 1.3', '>= 1.3.11'
