defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5000
  host: localhost
  username: dmitriy1
  password: 123

development:
  <<: *defaults
  database: db
  host: localhost

test:
  <<: *defaults
  database: db_test
  host: localhost

production:
  <<: *defaults
  database: db
  host: 127.0.0.0
  port: 5432
  username: dmitriy1
  password: 123
