defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: oleg
  password: rs4xvp5a

development:
  <<: *defaults
  database: db_development
  host: localhost

test:
  <<: *defaults
  database: db_test
  host: localhost

production:
  <<: *defaults
  database: db_production
  host: localhost
  username: test_name
  password: